### ISSUE TITLE
updating kibana views

### ISSUE THREAD

**Issue by kotter** [ChristianKniep/docker-elk#11]
Hey @ChristianKniep - hopefully quick question.  Is there a reason that the default console views in kibana are not externally linked to persist across restarts?  I'm at a bit of a sticking point where any work I save gets wiped out on restart of the container (thankfully nothing is in prod, so I'm just messing around at this point).  Would it be out of norm to provide the startup with another `-v` option linking to an external data container to persist views across restarts?

**Comment by ChristianKniep** [comment]
Hey @kotter,

what I would suggest is  create your own little Images (kotter/elk), for which the Dockerfile reads:
```
FROM qnib/elk
MAINTAINER "Christian Kniep <christian@qnib.org>"

## If you do not care about logging in via ssh
RUN rm /etc/supervisord.d/sshd.ini && \
    rm /etc/consul.d/check_sshd.json && \
    rm /etc/default/logstash/*
ADD etc/default/logstash/ /etc/default/logstash/
ADD var/www/kibana/app/dashboards/ /var/www/kibana/app/dashboards/
```
In case you want to develop on the dashboards bind-mount the dashboard-folder from this directory:
```
elk:
  image: kotter/elk
  ports:
   - "9200:9200"
   - "8080:80"
  hostname: elk
  volumes:
   - /var/lib/elasticsearch
   - ./var/www/kibana/app/dashboards/:/var/www/kibana/app/dashboards/
  privileged: true
```
By doing so you can save your dashboards as json-file, which you put into the docker folder.
If you restart the image it is going to be there, if you build it it is going to be baked in.
Persisting the dashboards in elasticsearch would be posibile as well, but I trust files more - maybe old fashioned. :)

How does that sound?
