### ISSUE TITLE
logstash restarting. 

### ISSUE THREAD

**Issue by fjoesne** [ChristianKniep/docker-elk#17]
Logstash keeps stopping for some reason, ironically I cant find any logs for it.. only the stdout/stderr that says:
```
elk_1 | 2015-11-29 20:35:07,614 INFO exited: logstash (exit status 1; not expected)
elk_1 | 2015-11-29 20:35:07,836 INFO spawned: 'logstash' with pid 26121
elk_1 | 2015-11-29 20:35:08,862 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
elk_1 | 2015-11-29 20:35:17,974 INFO exited: logstash (exit status 1; not expected)
elk_1 | 2015-11-29 20:35:17,991 INFO spawned: 'logstash' with pid 26222
```
Running 'service logstash restart' returns: 
```
/etc/init.d/logstash: line 41: .: /etc/default/logstash: is a directory
logstash started.
```

/etc/init.d/logstash: line 41: 
`[ -r /etc/default/$name ] && . /etc/default/$name`

(name=logstash)

I'm not sure how to deal with it without breaking something else. 

I can view logs in kibana, but I'm having trouble loading nginx pattern and I just want to make sure this is not the cause of the problem.

**Comment by ChristianKniep** [comment]
Could you please paste how you started the containers? Maybe the logstash directory was not mounted correctly. Are you following a specific blog post or readme?

**Comment by fjoesne** [comment]
using another nginx to publish/wrap it in ssl/auth. 
early and rough docker-compose.yml:
```
elk:
  image: qnib/elk
  restart: always
#  build: "docker-elk"
  ports:
#   - "9200:9200"
   - "5514:5514"
#   - "5601:5601"
#   - "8081:81"
#   - "8500:8500"
  environment:
  - DC_NAME=elk-server
  - RUN_SERVER=true
  - BOOTSTRAP_CONSUL=true
  - COLLECT_METRICS=false
  - FORWARD_TO_LOGSTASH=false
  dns: 127.0.0.1
  hostname: fjoesne-elk
  volumes:
   - /data/containerdata/fjoesne-elk/database:/var/lib/elasticsearch
   - /data/containerdata/fjoesne-elk/etc:/etc
  privileged: true
```
